services:
  - type: web
    name: bubble-tickets
    runtime: docker
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    dockerContext: .
    dockerfilePath: dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_ISSUER_URI
        sync: false
      - key: VITE_OIDC_AUTHORITY
        sync: false
      - key: VITE_OIDC_CLIENT_ID
        sync: false
      - key: VITE_OIDC_REDIRECT_URI
        sync: false
